package com.gmail.volkovskiyda.jellyshelf

import android.app.Application
import androidx.tracing.trace
import coil3.ImageLoader
import coil3.PlatformContext
import coil3.SingletonImageLoader
import com.gmail.volkovskiyda.jellyshelf.data.install.ApkInstaller
import com.gmail.volkovskiyda.jellyshelf.data.remote.UpdateFlags
import com.gmail.volkovskiyda.jellyshelf.di.appModule
import com.gmail.volkovskiyda.jellyshelf.domain.BuildInfo
import com.gmail.volkovskiyda.jellyshelf.domain.UpdateChecker
import com.gmail.volkovskiyda.jellyshelf.util.ActivityTracker
import com.gmail.volkovskiyda.jellyshelf.util.Traces
import com.google.firebase.crashlytics.FirebaseCrashlytics
import com.google.firebase.perf.FirebasePerformance
import io.kotzilla.generated.monitoring
import org.koin.android.ext.android.get
import org.koin.android.ext.koin.androidContext
import org.koin.androidx.workmanager.koin.workManagerFactory
import org.koin.core.context.startKoin
import timber.log.Timber

class JellyshelfApplication : Application(), SingletonImageLoader.Factory {

    // Everything after super.onCreate() is inside the trace section, and super itself is not:
    // Application.onCreate's base implementation is empty, and the SDK initialization that looks
    // like it belongs there (Firebase, WorkManager, profileinstaller) runs in ContentProviders
    // before this method is entered at all. See [Traces].
    override fun onCreate() {
        super.onCreate()
        trace(Traces.APP_ON_CREATE) { start() }
    }

    private fun start() {
        // The DI graph gets its own nested section: it is the one step here that grows with the
        // app, and a slow cold start should say whether the cost is Koin or one of the calls below.
        trace(Traces.START_KOIN) {
            startKoin {
                androidContext(this@JellyshelfApplication)
                // Register the Koin worker factory so workers declared with workerOf(...) get
                // constructor injection. The default WorkManager initializer is removed in the
                // manifest so this is the sole initialization path (see AndroidManifest.xml).
                workManagerFactory()
                modules(appModule)
                // Kotzilla, last in the block as its docs require: it attaches to the Koin
                // instance this call is configuring, so every module above must already be
                // declared. The SDK itself is usually running by now — its initializer boots it
                // before onCreate is entered — and this is what hands it the graph to watch.
                // Generated by the Gradle plugin from app/kotzilla.json. When that file is absent
                // the plugin is disabled and generates nothing at all, so a keyless checkout gets
                // the hand-written no-op in src/kotzillaDisabled instead and still compiles —
                // this call never changes. The cost lands inside Traces.START_KOIN deliberately:
                // that section exists to say whether a slow start is Koin or something beside it,
                // and this is part of Koin's bill.
                monitoring()
            }
        }
        // Registered before anything can navigate, so the tracker never misses the first activity.
        // The tester sign-in needs a foreground Activity to open its Custom Tab into this app's
        // task, and needs to see the redirect land to close it again — neither is answerable from
        // an application context. See TesterSignInLauncher.
        registerActivityLifecycleCallbacks(get<ActivityTracker>())
        // Read after Koin starts so the flag comes from the injected BuildInfo (the single source
        // of truth), and shared by the two gates below rather than resolved from the graph twice.
        val isDebug = get<BuildInfo>().isDebug
        // Release plants no tree, so every Timber call is a no-op at runtime — and R8's
        // -assumenosideeffects rules (src/main/keepRules) strip the calls from release bytecode
        // entirely.
        if (isDebug) {
            Timber.plant(Timber.DebugTree())
        }
        // The inverse gate: only release builds report crashes and perf traces, so the dashboards
        // describe real usage — development crashes never dilute the crash-free-users metric and
        // dev/emulator runs never pollute the performance trends. Both SDKs persist this flag, so
        // setting it on every start is what keeps a build that changes type from inheriting the
        // previous answer.
        FirebaseCrashlytics.getInstance().setCrashlyticsCollectionEnabled(!isDebug)
        FirebasePerformance.getInstance().isPerformanceCollectionEnabled = !isDebug
        // The cold-start update check, here rather than in a composable's LaunchedEffect(Unit):
        // onCreate runs exactly once per process, while "once per composition" is a weaker promise
        // than it looks under configuration changes and the theme reveal's uiMode handling. It
        // returns immediately unless a release build has opted into a channel, and never blocks —
        // it only launches work on the application scope. UpdateChecker documents every gate.
        get<UpdateFlags>().refresh()
        get<UpdateChecker>().checkOnStart()
        // And the daily one, which the launch check cannot stand in for: the whole point is the
        // user who does not launch. Unlike periodic sync below, re-stating this every start is
        // correct — it is cancelled by turning the channel off, which is persisted state this
        // reads back and honours, not by an act it would undo.
        get<UpdateChecker>().scheduleBackgroundCheck()
        // A download interrupted by the process dying leaves a part-file nothing else will clean
        // up. Cheap, and the cache is the one place where leaving rubbish is purely our fault.
        ApkInstaller.sweep(this)
        // Periodic sync is deliberately NOT scheduled here: WorkManager persists it across
        // launches, and re-scheduling on every start would undo the wipe Sign out performs, which
        // cancels it. "Sync now" owns creating it (see SyncScheduler).
    }

    /**
     * Coil's singleton hook: `SingletonImageLoader` detects that the `Application` implements this
     * factory, so every `AsyncImage` resolves its loader through here and the tuned client in
     * [com.gmail.volkovskiyda.jellyshelf.di.appModule] applies without threading an `ImageLoader`
     * through the composables. Called lazily on the first image request, long after [startKoin], so
     * resolving from the graph here is safe. [context] is ignored for the same reason: the loader
     * is built from the Koin `androidContext()`, which is this application.
     */
    override fun newImageLoader(context: PlatformContext): ImageLoader = get()
}
